### PR TITLE
Ignore properties annotated with JsonIgnore

### PR DESCRIPTION
**Pull request by sajithdilshan**
When generating docs, ignore properties annotated with JsonIgnore

### CODE REVIEW

**Comment by jmisur** [comment]
I thought this works out of the box. We shouldn't manually inspect Jackson annotations, the framework should do it for us.

**Comment by sajithdilshan** [comment]
@jmisur It doesn't work out of the box. Florian is looking into why it is not working. This PR is to be used as the last resort :)

**Comment by fbenz** [comment]
The test stays green even without the changes in `FieldDocumentationObjectVisitor` and thus it works out of the box. There is already a test that includes `@JsonIgnore`: `testGenerateDocumentationForJacksonAnnotations`. So it might be something else that caused you to still see fields that should be hidden. Therefore, I suggest to close this PR and investigate what is happening in your case.

**Comment by sajithdilshan** [comment]
@fbenz You are correct. I've testes JsonIgnore annotation with rest-doc in a standalone project and it works.

**Pull request closed without merging**
