### PR TITLE
Kotlin WebMVC Sample: Switch to JUnit 5 and upgrade dependencies

### PR DESCRIPTION
**Pull request by fbenz**
I also updated the README of the Dokka extension because it became outdated.

### CODE REVIEW

**Comment by fbenz** [comment]
The build on Travis CI is green but not shown here: https://travis-ci.org/github/ScaCap/spring-auto-restdocs/builds/721838388

**Review by jmisur — APPROVED** [review]
We could maybe mention this somewhere in the docs/readme, which sample is in which junit.

**Comment by fbenz** [comment]
@jmisur I added a list with the sample projects and the used technologies to the Readme.

**Comment by jmisur** [comment]
👍

**Pull request merged**
