### PR TITLE
Optionally use javax.validation

### LINKED ISSUE #124: Do not pull hibernate validator transitively
I have a project where we actually do not use hibernate validator. The dependency is being pulled automatically by auto-restdocs which means that it is failing as I don't have implementation of the el-api in my dependencies.

I would propose that you make the hibernate-validator a provided dependency and only instantiate the `ConstraintReaderImpl` if hibernate is present, or even make it so that you can configure the `JacksonPreparingResultHandler`.

### PR DESCRIPTION
**Pull request by filiphr**
This PR fixes #124. More specifically https://github.com/filiphr/spring-auto-restdocs/commit/25bf9d73f4297e01e9593ff79b8623ad0d71839a fixes it.

In order to test this you actually need an integration test that does not pull in the java validation things. I created a copy of the example and excluded the hibernate validator. 

It was something that I could wrap up fast. We can thing of a better way to test this, or even completely remove the example...

### CODE REVIEW

**Comment by jmisur** [comment]
Thanks for this PR. I tried similar thing as you with the example project. We'll have a look at it this week.

**Comment by filiphr** [comment]
No problem @jmisur, let me know if something needs to be changed

**Comment by filiphr** [comment]
@jmisur I just wanted to ask you if there is something else that needs to be done for this PR to get accepted.

**Comment by jmisur** [comment]
I need to experiment a bit more. Unfortunately the copy of our example project is not enough to make it.

**Comment by jmisur** [comment]
Can you please test #149 if it works for you?

**Comment by jmisur** [comment]
Closing in favor of #149

**Pull request closed without merging**
