### PR TITLE
Upgrade to Spring REST Docs 2.0.0

### LINKED ISSUE #176: Upgrade to Spring REST Docs 2.0.0
~~This upgrade should involve adding support for WebTestClient and thus involves some work.~~

We have to be aware that Spring REST Docs 2 requires Java 8 and Spring Framework 5.

### PR DESCRIPTION
**Pull request by fbenz**
Branch to experiment with Spring REST Docs 2.0.0. We know that this version requires Spring Framework 5.0 and Java 8 and thus forces these requirements on Spring Auto REST Docs users.

Closes #176

### CODE REVIEW

**Comment by fbenz** [comment]
As expected the Java 7 build is failing with `UnsupportedClassVersionError`.

**Comment by jmisur** [comment]
I would just maybe create another example project based on spring-boot 2 / restdocs 2 to ensure compatibility, but we cannot upgrade entire auto restdocs otherwise we lose support for non-2 version.

**Comment by fbenz** [comment]
I upgraded the example project to Spring Boot 2 and did not create a separate one. Reason is that Spring REST Docs 2 requires Spring Framework 5 and thus only supports Spring Boot 2. It worked with our existing Spring Boot 1 example, but is is not officially supported.

If we want to support a version based on Spring REST Docs 1 and another one based on Spring REST Docs 2 at the same time, we have to release one version out of a branch. Spring REST Docs does the same: version 2 is on master and 1.2.x on a branch, see https://github.com/spring-projects/spring-restdocs/tree/1.2.x

**Comment by jmisur** [comment]
let's do the branch approach when our "main" project runs on sb2

**Comment by fbenz** [comment]
spring-auto-restdocs-json-doclet does not build with JDK9 yet:
```
[ERROR] Failed to execute goal on project spring-auto-restdocs-json-doclet: Could not resolve dependencies for project capital.scalable:spring-auto-restdocs-json-doclet:jar:2.0.0-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.4.2 at specified path /usr/lib/jvm/java-9-oracle/../lib/tools.jar -> 
```
For JDK9 there are instructions here https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/package-summary.html
But I don't know how to change the Doclet to work both with both JDK8 and JDK9 yet. Looks like it requires some research.

**Comment by fbenz** [comment]
Looks like we will have to create a separate doclet for JDK9+. The API changed completely with "JEP 221: New Doclet API" and thus it does not make sense to try to combine this into one version. Other projects are also going the same path and are overing two doclets: one for JDK8 and lower and one for JDK9+.

**Comment by fbenz** [comment]
This branch is ready now.

**Comment by fbenz** [comment]
Yes, I would do the following steps

1. Branch of master to create a v1.x branch.
2. Merge this branch into master.
3. The Kotlin branch could then be merged into master, because there would be no more JDK7 issue. The small change to the spring-auto-restdocs-core can also be added to the v1.x version. This way one could use the Dokka extension with both Auto REST Docs versions.
4. Release 1.0.12 and 2.0.0

**Pull request merged**
