### PR TITLE
#424: added "hal+json" as compatible content type for  ArrayLimitingJsonContentModifier

### PR DESCRIPTION
**Pull request by mustaphazorgati**
Since I didn't find any existing test class I didn't bother writing a test..

### CODE REVIEW

**Comment by mustaphazorgati** [comment]
I just did some research about media types and their compatibility. 
According to [RFC6839](https://tools.ietf.org/html/rfc6839#section-3.1): 
> The suffix "+json" MAY be used with any media type whose representation follows that established for "application/json"

Your incentive that a spring utility must provide it made me stumple across this [issue](https://github.com/spring-projects/spring-framework/issues/21045). According to that issue some other RFCs (not listed) define that "application/hal+json" is not compatible with "application/json". Even tho they share the same syntax (from RFC6839). 
I suggest changing the predicate to the recommended one within that issue.

How does that sound?

**Comment by jmisur** [comment]
Thanks for digging into this. That suggestion on the linked issue sounds like it will solve it.

**Comment by mustaphazorgati** [comment]
@jmisur PR is ready for review :)

**Comment by jmisur** [comment]
Please check the Travis log - ResponseModifyingPreprocessorsTest failed.

**Comment by mustaphazorgati** [comment]
My bad. I didn't read properly earlier today. In order to support any +json structured Syntax Suffix (which is something else using the json syntax) we have to test two compatiblities: Without any suffix `application/json` and with any suffix `application/*+json`.
The referenced issue said that according to the RFCs `application/*+json` is compatible to `application/hal+json`.

**Comment by mustaphazorgati** [comment]
I added some tests to explicitly show the new compatibility for both cases.

**Review by jmisur — APPROVED** [review]
👍

**Pull request merged**
